name: Build
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: tubi
          POSTGRES_USER: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      kafka:
        image: wurstmeister/kafka:latest
        ports:
          - 29092:9092
        env:
          KAFKA_ADVERTISED_LISTENERS: INSIDE://broker:9093,OUTSIDE://broker:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:29092
          KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    strategy:
      matrix:
        image_name: ["api-gateway", "discovery-server", "processor-service","project-service","task-service"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Build
        working-directory: ${{ matrix.image_name }}
        run: |
          mvn package
          mv target/*.jar app.jar

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Extract image metadata for ${{ matrix.image_name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
        env:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
